#!/usr/bin/env node
// Joins lib/index.json, docs/component-notes.json and lib/skips.json into
// lib/CATALOG.md — the human-readable list of what a journey can be built
// from.
//
//   node scripts/build-catalog.mjs [--index lib/index.json]
//     [--notes docs/component-notes.json] [--skips lib/skips.json]
//     [--out lib/CATALOG.md]
//
// Three artifacts, three audiences: index.json is what the agents read,
// CATALOG.md is what developers skim, skips.json is the record of what was
// deliberately left out. Deferred components appear here too — a developer
// hunting for a date picker should find "deferred: needs the open-state
// harness", not silence, because silence reads as "we forgot" and invites a
// hand-rolled substitute.
//
// The "use when" column is not invented here. It comes from the narrative
// standard via docs/component-notes.json, so the guidance a developer reads
// is the firm's own wording rather than a generated guess.

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { dirname, resolve, isAbsolute } from "node:path";
import { fileURLToPath } from "node:url";

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const argv = process.argv.slice(2);
const flag = (n, d) => {
  const i = argv.indexOf(`--${n}`);
  return i >= 0 && argv[i + 1]
    ? (isAbsolute(argv[i + 1]) ? argv[i + 1] : resolve(process.cwd(), argv[i + 1]))
    : resolve(REPO, d);
};
const indexPath = flag("index", "lib/index.json");
const notesPath = flag("notes", "docs/component-notes.json");
const skipsPath = flag("skips", "lib/skips.json");
const outPath = flag("out", "lib/CATALOG.md");

const read = (p, req) => {
  if (!existsSync(p)) {
    if (req) { console.error(`ERROR: ${p} not found`); process.exit(1); }
    return null;
  }
  try { return JSON.parse(readFileSync(p, "utf8")); }
  catch (e) { console.error(`ERROR: ${p} is not valid JSON: ${e.message}`); process.exit(1); }
};

const index = read(indexPath, true);
const notes = read(notesPath, false) ?? {};
const skips = read(skipsPath, false) ?? {};

// index.json is keyed "Component/variant"; group back into components.
const byComponent = new Map();
for (const [key, meta] of Object.entries(index.entries ?? index)) {
  if (key.startsWith("$")) continue;
  const [component, variant = "default"] = key.split("/");
  if (!byComponent.has(component)) {
    byComponent.set(component, { variants: new Set(), sizes: new Set(), contains: new Set(), entries: 0 });
  }
  const c = byComponent.get(component);
  c.variants.add(variant);
  c.entries++;
  for (const s of meta?.sizes ?? []) c.sizes.add(s);
  for (const n of meta?.contains ?? []) c.contains.add(n);
  if (meta?.width && !c.size) c.size = `${meta.width}x${meta.height}`;
  if (meta?.resize && !c.resize) c.resize = meta.resize;
}

const noteFor = (component) => {
  const n = notes[component];
  if (!n) return "";
  return (typeof n === "string" ? n : n.useWhen ?? n.description ?? "").replace(/\s+/g, " ").trim();
};

const missingNotes = [];
const rows = [...byComponent.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([component, c]) => {
  const note = noteFor(component);
  if (!note) missingNotes.push(component);
  return `| \`${component}\` | ${[...c.variants].sort().join(", ")} | ${[...c.sizes].sort().join(", ") || "—"} | ${c.entries} | ${note || "_(no note in the standard)_"} |`;
});

const skipRows = Object.entries(skips.components ?? {})
  .filter(([k]) => !k.startsWith("$"))
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([component, s]) => `| \`${component}\` | ${s.bucket ?? "—"} | ${(s.reason ?? "").replace(/\s+/g, " ")} |`);

const composites = [...byComponent.entries()].filter(([, c]) => c.contains.size);

const md = `# UDS component catalogue

_Generated by \`scripts/build-catalog.mjs\` — do not hand-edit. Regenerated
whenever the library is rebuilt._

What you can build a journey from. Describe what a screen needs in plain
language and the sketcher picks components for you; use this when you want
to name one specifically, or to judge a substitution it proposes.

## Available — ${byComponent.size} components, ${[...byComponent.values()].reduce((n, c) => n + c.entries, 0)} library entries

| Component | Variants | Sizes | Entries | Use when |
|---|---|---|---:|---|
${rows.join("\n")}
${composites.length ? `
### Composites

These place several components at once; the nested pieces come with them.

${composites.map(([c, m]) => `- \`${c}\` contains ${[...m.contains].map((x) => `\`${x}\``).join(", ")}`).join("\n")}
` : ""}
${skipRows.length ? `
## Deferred — ${skipRows.length}

Present in the kit but not (yet) in the shape library. If a journey needs
one, say so: the fix is to extend the library, never to hand-draw a
substitute.

| Component | Bucket | Why |
|---|---|---|
${skipRows.join("\n")}
` : ""}
---

Agents read \`lib/index.json\`, not this file. If the two disagree, the index
wins and this catalogue is stale — rebuild it.
`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, md);
console.log(`wrote ${outPath}`);
console.log(`  ${byComponent.size} components, ${skipRows.length} deferred`);
if (missingNotes.length) {
  console.log(`  ${missingNotes.length} without a "use when" note: ${missingNotes.slice(0, 8).join(", ")}${missingNotes.length > 8 ? "…" : ""}`);
  console.log(`  (add them to ${notesPath} via standards-curator — the text belongs to the standard, not here)`);
}
