#!/usr/bin/env node
// Fetches the sanctioned brand logo once and writes it to lib/logo.json as a
// base64 data URL, so mockups can actually show it.
//
//   node scripts/embed-logo.mjs <logo-url> [--out lib/logo.json]
//
// Run this from inside the firm network, where the asset host is reachable.
// Commit the result: it is small, it changes only when the brand mark does,
// and every generated scene needs it.
//
// Why a data URL: Excalidraw renders images only from its own `files` map,
// keyed by an image element's fileId. It never fetches a remote src — which
// is why a URL-only logo shows as an empty box. The sanctioned URL is still
// recorded (as `src` here and in customData.props.src on the element), so
// codegen emits the correct <img> tag; the embedded copy exists purely so
// reviewers can see the brand mark in the mockup.

import { writeFileSync } from "node:fs";

const url = process.argv[2];
const outIdx = process.argv.indexOf("--out");
const out = outIdx >= 0 && process.argv[outIdx + 1] ? process.argv[outIdx + 1] : "lib/logo.json";

if (!url) {
  console.error("usage: node scripts/embed-logo.mjs <logo-url> [--out lib/logo.json]");
  console.error("       the URL is the one marked CRITICAL in docs/uds-standards.md");
  process.exit(2);
}

const MIME = { png: "image/png", jpg: "image/jpeg", jpeg: "image/jpeg", svg: "image/svg+xml", webp: "image/webp" };

const res = await fetch(url).catch((e) => {
  console.error(`ERROR: could not fetch ${url}: ${e.message}`);
  console.error("Run this from inside the firm network, or download the file and pass a file:// URL.");
  process.exit(1);
});
if (!res.ok) {
  console.error(`ERROR: ${url} returned ${res.status} ${res.statusText}`);
  process.exit(1);
}

const buf = Buffer.from(await res.arrayBuffer());
const ext = (url.split("?")[0].split(".").pop() ?? "png").toLowerCase();
const mimeType = res.headers.get("content-type")?.split(";")[0] || MIME[ext] || "image/png";

// PNG dimensions live in the IHDR chunk at a fixed offset; other formats are
// left to the caller, since only the aspect ratio matters downstream.
let width = null;
let height = null;
if (mimeType === "image/png" && buf.length > 24 && buf.toString("ascii", 12, 16) === "IHDR") {
  width = buf.readUInt32BE(16);
  height = buf.readUInt32BE(20);
}

const payload = {
  $comment: [
    "Brand logo, embedded so Excalidraw can render it. Excalidraw reads images",
    "from a scene's files map, never from a remote URL — a URL-only logo shows",
    "as an empty box. Generated by scripts/embed-logo.mjs; do not hand-edit.",
    "`src` remains the authority for generated code.",
  ],
  id: "logo-uds",
  src: url,
  mimeType,
  naturalWidth: width,
  naturalHeight: height,
  dataURL: `data:${mimeType};base64,${buf.toString("base64")}`,
};

writeFileSync(out, JSON.stringify(payload, null, 2));
const kb = (payload.dataURL.length / 1024).toFixed(1);
console.log(`wrote ${out} — ${mimeType}, ${width ?? "?"}x${height ?? "?"}, ${kb} KB as base64`);
if (payload.dataURL.length > 512 * 1024) {
  console.log("WARN: over 512 KB; every scene embeds a copy, so consider a smaller asset");
}
