#!/usr/bin/env node
// Makes a TypeScript AST parser available to the extraction scripts without
// touching the kit repo's own dependencies.
//
//   node scripts/ensure-parser.mjs          # bootstrap, print the resolved path
//   import { loadTsMorph } from "./ensure-parser.mjs"   # from another script
//
// Why this exists: `pnpm add -D ts-morph` in the kit repo root does not
// install ts-morph — it re-resolves the *entire* package.json first. A firm
// kit lists private packages (@uwr/icons and friends) that a developer's
// configured registry may not serve, so the install dies on a package that
// has nothing to do with parsing TypeScript. A pilot run burned several
// minutes cycling through pnpm, npm, a regex rewrite, and a hand-built temp
// directory before landing on what this script does deterministically.
//
// The parser is tooling, not a dependency of the kit. It is installed into
// .uijourney-tools/ — a sandbox with its own package.json naming ts-morph and
// nothing else, so the registry is never asked for a private package — and
// that directory is gitignored, keeping the extraction MR free of lockfile
// churn. ts-morph bundles its own typescript, so this is a single install.

import { createRequire } from "node:module";
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SANDBOX = join(REPO_ROOT, ".uijourney-tools");
const SPEC = process.env.UIJOURNEY_TS_MORPH_VERSION ?? "ts-morph@^21";

const require = createRequire(import.meta.url);

function tryResolve() {
  const paths = [join(SANDBOX, "node_modules"), REPO_ROOT, join(REPO_ROOT, "node_modules")];
  try {
    return require.resolve("ts-morph", { paths });
  } catch {
    return null;
  }
}

function install() {
  mkdirSync(SANDBOX, { recursive: true });
  const pkg = join(SANDBOX, "package.json");
  if (!existsSync(pkg)) {
    // A package.json listing nothing but the parser. npm resolves only what
    // it finds here, so the kit's private packages never enter the tree.
    writeFileSync(
      pkg,
      JSON.stringify(
        { name: "uijourney-tools", version: "0.0.0", private: true, description: "Isolated parser sandbox for UIJourney extraction scripts. Generated by scripts/ensure-parser.mjs; not part of the kit." },
        null,
        2
      ) + "\n"
    );
  }
  console.error(`ts-morph not found; installing ${SPEC} into .uijourney-tools/ ...`);
  // cwd is the sandbox: npm still walks up for .npmrc (so the firm's registry
  // and proxy settings apply) but reads dependencies only from the sandbox.
  execFileSync("npm", ["install", SPEC, "--no-audit", "--no-fund"], {
    cwd: SANDBOX,
    stdio: ["ignore", "inherit", "inherit"],
  });
}

export async function loadTsMorph() {
  let entry = tryResolve();
  if (!entry) {
    try {
      install();
    } catch (e) {
      console.error(
        `\nERROR: could not install ${SPEC}.\n` +
          `The failure above is from npm talking to your configured registry, and it is\n` +
          `about ts-morph itself — the kit's own dependencies are not part of this install.\n\n` +
          `If your registry genuinely does not carry ts-morph, ask for it to be mirrored.\n` +
          `Do NOT fall back to parsing cva() with regular expressions: variant axes get\n` +
          `silently under-reported, and because library coverage is measured against the\n` +
          `manifest, nothing downstream can detect the loss.\n`
      );
      throw e;
    }
    entry = tryResolve();
    if (!entry) throw new Error("ts-morph installed but still not resolvable from .uijourney-tools/");
  }
  return import(pathToFileURL(entry).href);
}

export function tsMorphNodeModules() {
  return join(SANDBOX, "node_modules");
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  await loadTsMorph();
  const entry = tryResolve();
  let version = "unknown";
  try {
    version = require(join(entry.split("node_modules")[0], "node_modules", "ts-morph", "package.json")).version;
  } catch {}
  console.log(`ts-morph ${version} ready`);
  console.log(entry);
}
